version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api
      - VITE_ADMIN_PASSWORD=${ADMIN_PASSWORD:-florida2024}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/florida_technik
      - PORT=5001
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: 