version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5001/api}
      - VITE_ADMIN_PASSWORD=${ADMIN_PASSWORD:-florida2024}

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: 