version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8081/api}
    ports:
      - "8080:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8081/api}
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ../server
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8081:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/florida
      - PORT=5000
      - JWT_SECRET=matematik
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: 