name: Deploy to Server

on:
  push:
    branches:
      - main  # oder master, je nachdem welchen Branch du verwendest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /pfad/zu/florida-technik
            git pull
            docker-compose down
            docker-compose up -d --build 